### ISSUE TITLE
native node async/await test

### ISSUE THREAD

**Issue by toshok** [honeycombio/beeline-nodejs#71] opened 2018-07-24 15:48 UTC
context doesn't seem to get propagated for native node async/await usage.

**Comment by toshok** [comment] 2018-07-24 20:19
This looks relevant https://github.com/nodejs/node/issues/20404

**Comment by BrianChristie** [comment] 2018-08-09 18:25
Looks like nodejs/node#20404 is a duplicate of nodejs/node#20274

[One of the comments on 20274](https://github.com/nodejs/node/issues/20274#issuecomment-395200647) says:
> It looks like this is fixed in 10.4.0 with the update of V8 from 6.6 to 6.7

**Comment by vreynolds** [comment] 2021-12-27 20:01
Hello,

We will be closing this issue as it is a low priority for us. It is unlikely that we'll ever get to it, and so we'd like to set expectations accordingly.

As we enter 2022 Q1, we are trimming our OSS backlog. This is so that we can focus better on areas that are more aligned with the OpenTelemetry-focused direction of telemetry ingest for Honeycomb.

If this issue is important to you, please feel free to ping here and we can discuss/re-open.

**Closed by vreynolds** 2021-12-27 20:01 UTC
Labels: type: maintenance
